// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: api/wallet/v1/waller.proto

package wallet_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 充值状态
type RechargeStatus int32

const (
	RechargeStatus_RECHARGE_STATUS_UNSPECIFIED RechargeStatus = 0
	RechargeStatus_RECHARGE_STATUS_PENDING     RechargeStatus = 1
	RechargeStatus_RECHARGE_STATUS_CONFIRMED   RechargeStatus = 2
	RechargeStatus_RECHARGE_STATUS_FAILED      RechargeStatus = 3
)

// Enum value maps for RechargeStatus.
var (
	RechargeStatus_name = map[int32]string{
		0: "RECHARGE_STATUS_UNSPECIFIED",
		1: "RECHARGE_STATUS_PENDING",
		2: "RECHARGE_STATUS_CONFIRMED",
		3: "RECHARGE_STATUS_FAILED",
	}
	RechargeStatus_value = map[string]int32{
		"RECHARGE_STATUS_UNSPECIFIED": 0,
		"RECHARGE_STATUS_PENDING":     1,
		"RECHARGE_STATUS_CONFIRMED":   2,
		"RECHARGE_STATUS_FAILED":      3,
	}
)

func (x RechargeStatus) Enum() *RechargeStatus {
	p := new(RechargeStatus)
	*p = x
	return p
}

func (x RechargeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RechargeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_wallet_v1_waller_proto_enumTypes[0].Descriptor()
}

func (RechargeStatus) Type() protoreflect.EnumType {
	return &file_api_wallet_v1_waller_proto_enumTypes[0]
}

func (x RechargeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RechargeStatus.Descriptor instead.
func (RechargeStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_wallet_v1_waller_proto_rawDescGZIP(), []int{0}
}

type RechargeListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Status        RechargeStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=wallet.v1.RechargeStatus" json:"status,omitempty"`
	Page          int64                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeListReq) Reset() {
	*x = RechargeListReq{}
	mi := &file_api_wallet_v1_waller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeListReq) ProtoMessage() {}

func (x *RechargeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_wallet_v1_waller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeListReq.ProtoReflect.Descriptor instead.
func (*RechargeListReq) Descriptor() ([]byte, []int) {
	return file_api_wallet_v1_waller_proto_rawDescGZIP(), []int{0}
}

func (x *RechargeListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RechargeListReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *RechargeListReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RechargeListReq) GetStatus() RechargeStatus {
	if x != nil {
		return x.Status
	}
	return RechargeStatus_RECHARGE_STATUS_UNSPECIFIED
}

func (x *RechargeListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RechargeListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// 单条充值记录
type RechargeListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	FromAddress   string                 `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	ToUid         int64                  `protobuf:"varint,4,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	Chain         string                 `protobuf:"bytes,5,opt,name=chain,proto3" json:"chain,omitempty"`
	Symbol        string                 `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount        string                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"` // decimal.Decimal 建议字符串存储，保持精度
	Status        RechargeStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=wallet.v1.RechargeStatus" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,9,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	BlockHeight   int64                  `protobuf:"varint,10,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	LogIndex      int32                  `protobuf:"varint,11,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeListItem) Reset() {
	*x = RechargeListItem{}
	mi := &file_api_wallet_v1_waller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeListItem) ProtoMessage() {}

func (x *RechargeListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_wallet_v1_waller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeListItem.ProtoReflect.Descriptor instead.
func (*RechargeListItem) Descriptor() ([]byte, []int) {
	return file_api_wallet_v1_waller_proto_rawDescGZIP(), []int{1}
}

func (x *RechargeListItem) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *RechargeListItem) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *RechargeListItem) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *RechargeListItem) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *RechargeListItem) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *RechargeListItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RechargeListItem) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RechargeListItem) GetStatus() RechargeStatus {
	if x != nil {
		return x.Status
	}
	return RechargeStatus_RECHARGE_STATUS_UNSPECIFIED
}

func (x *RechargeListItem) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *RechargeListItem) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *RechargeListItem) GetLogIndex() int32 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *RechargeListItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RechargeListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RechargeListItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeListResp) Reset() {
	*x = RechargeListResp{}
	mi := &file_api_wallet_v1_waller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeListResp) ProtoMessage() {}

func (x *RechargeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_wallet_v1_waller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeListResp.ProtoReflect.Descriptor instead.
func (*RechargeListResp) Descriptor() ([]byte, []int) {
	return file_api_wallet_v1_waller_proto_rawDescGZIP(), []int{2}
}

func (x *RechargeListResp) GetItems() []*RechargeListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RechargeListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ApplyWithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ToAddress     string                 `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"` // decimal.Decimal 建议字符串存储，保持精度
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWithdrawReq) Reset() {
	*x = ApplyWithdrawReq{}
	mi := &file_api_wallet_v1_waller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWithdrawReq) ProtoMessage() {}

func (x *ApplyWithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_wallet_v1_waller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWithdrawReq.ProtoReflect.Descriptor instead.
func (*ApplyWithdrawReq) Descriptor() ([]byte, []int) {
	return file_api_wallet_v1_waller_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyWithdrawReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ApplyWithdrawReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ApplyWithdrawReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ApplyWithdrawReq) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *ApplyWithdrawReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ApplyWithdrawReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApplyWithdrawResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWithdrawResp) Reset() {
	*x = ApplyWithdrawResp{}
	mi := &file_api_wallet_v1_waller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWithdrawResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWithdrawResp) ProtoMessage() {}

func (x *ApplyWithdrawResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_wallet_v1_waller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWithdrawResp.ProtoReflect.Descriptor instead.
func (*ApplyWithdrawResp) Descriptor() ([]byte, []int) {
	return file_api_wallet_v1_waller_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyWithdrawResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyWithdrawResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_api_wallet_v1_waller_proto protoreflect.FileDescriptor

const file_api_wallet_v1_waller_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/wallet/v1/waller.proto\x12\twallet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\x0fRechargeListReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.wallet.v1.RechargeStatusR\x06status\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\"\x95\x03\n" +
	"\x10RechargeListItem\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12!\n" +
	"\ffrom_address\x18\x02 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x15\n" +
	"\x06to_uid\x18\x04 \x01(\x03R\x05toUid\x12\x14\n" +
	"\x05chain\x18\x05 \x01(\tR\x05chain\x12\x16\n" +
	"\x06symbol\x18\x06 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\x121\n" +
	"\x06status\x18\b \x01(\x0e2\x19.wallet.v1.RechargeStatusR\x06status\x12\x1b\n" +
	"\terror_msg\x18\t \x01(\tR\berrorMsg\x12!\n" +
	"\fblock_height\x18\n" +
	" \x01(\x03R\vblockHeight\x12\x1b\n" +
	"\tlog_index\x18\v \x01(\x05R\blogIndex\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"[\n" +
	"\x10RechargeListResp\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.wallet.v1.RechargeListItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa8\x01\n" +
	"\x10ApplyWithdrawReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"to_address\x18\x04 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"J\n" +
	"\x11ApplyWithdrawResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg*\x89\x01\n" +
	"\x0eRechargeStatus\x12\x1f\n" +
	"\x1bRECHARGE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RECHARGE_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19RECHARGE_STATUS_CONFIRMED\x10\x02\x12\x1a\n" +
	"\x16RECHARGE_STATUS_FAILED\x10\x032\xa4\x01\n" +
	"\x06Wallet\x12N\n" +
	"\x13GetRechargeListById\x12\x1a.wallet.v1.RechargeListReq\x1a\x1b.wallet.v1.RechargeListResp\x12J\n" +
	"\rApplyWithdraw\x12\x1b.wallet.v1.ApplyWithdrawReq\x1a\x1c.wallet.v1.ApplyWithdrawRespB\x19Z\x17api/wallet/v1;wallet_v1b\x06proto3"

var (
	file_api_wallet_v1_waller_proto_rawDescOnce sync.Once
	file_api_wallet_v1_waller_proto_rawDescData []byte
)

func file_api_wallet_v1_waller_proto_rawDescGZIP() []byte {
	file_api_wallet_v1_waller_proto_rawDescOnce.Do(func() {
		file_api_wallet_v1_waller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_wallet_v1_waller_proto_rawDesc), len(file_api_wallet_v1_waller_proto_rawDesc)))
	})
	return file_api_wallet_v1_waller_proto_rawDescData
}

var file_api_wallet_v1_waller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_wallet_v1_waller_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_wallet_v1_waller_proto_goTypes = []any{
	(RechargeStatus)(0),           // 0: wallet.v1.RechargeStatus
	(*RechargeListReq)(nil),       // 1: wallet.v1.RechargeListReq
	(*RechargeListItem)(nil),      // 2: wallet.v1.RechargeListItem
	(*RechargeListResp)(nil),      // 3: wallet.v1.RechargeListResp
	(*ApplyWithdrawReq)(nil),      // 4: wallet.v1.ApplyWithdrawReq
	(*ApplyWithdrawResp)(nil),     // 5: wallet.v1.ApplyWithdrawResp
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_wallet_v1_waller_proto_depIdxs = []int32{
	0, // 0: wallet.v1.RechargeListReq.status:type_name -> wallet.v1.RechargeStatus
	0, // 1: wallet.v1.RechargeListItem.status:type_name -> wallet.v1.RechargeStatus
	6, // 2: wallet.v1.RechargeListItem.created_at:type_name -> google.protobuf.Timestamp
	2, // 3: wallet.v1.RechargeListResp.items:type_name -> wallet.v1.RechargeListItem
	1, // 4: wallet.v1.Wallet.GetRechargeListById:input_type -> wallet.v1.RechargeListReq
	4, // 5: wallet.v1.Wallet.ApplyWithdraw:input_type -> wallet.v1.ApplyWithdrawReq
	3, // 6: wallet.v1.Wallet.GetRechargeListById:output_type -> wallet.v1.RechargeListResp
	5, // 7: wallet.v1.Wallet.ApplyWithdraw:output_type -> wallet.v1.ApplyWithdrawResp
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_wallet_v1_waller_proto_init() }
func file_api_wallet_v1_waller_proto_init() {
	if File_api_wallet_v1_waller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_wallet_v1_waller_proto_rawDesc), len(file_api_wallet_v1_waller_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_wallet_v1_waller_proto_goTypes,
		DependencyIndexes: file_api_wallet_v1_waller_proto_depIdxs,
		EnumInfos:         file_api_wallet_v1_waller_proto_enumTypes,
		MessageInfos:      file_api_wallet_v1_waller_proto_msgTypes,
	}.Build()
	File_api_wallet_v1_waller_proto = out.File
	file_api_wallet_v1_waller_proto_goTypes = nil
	file_api_wallet_v1_waller_proto_depIdxs = nil
}
