// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: api/user/v1/user.proto

package user_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0 // 默认零值
	UserStatus_USER_STATUS_DISABLED    UserStatus = 1 // 禁用
	UserStatus_USER_STATUS_ENABLED     UserStatus = 2 // 启用
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_DISABLED",
		2: "USER_STATUS_ENABLED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_DISABLED":    1,
		"USER_STATUS_ENABLED":     2,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_api_user_v1_user_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{0}
}

// 钱包地址信息
type AddressInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`     // "BTC", "ETH"
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // "0x..."
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInfo) Reset() {
	*x = AddressInfo{}
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInfo) ProtoMessage() {}

func (x *AddressInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInfo.ProtoReflect.Descriptor instead.
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *AddressInfo) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *AddressInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// 核心用户信息 (不包含密码！)
type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        UserStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=user.v1.UserStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`         // Unix 时间戳 (秒)
	LastLoginAt   int64                  `protobuf:"varint,7,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"` // Unix 时间戳 (秒)
	Addresses     []*AddressInfo         `protobuf:"bytes,8,rep,name=addresses,proto3" json:"addresses,omitempty"`                           // 用户关联的地址列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserProfile) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *UserProfile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserProfile) GetLastLoginAt() int64 {
	if x != nil {
		return x.LastLoginAt
	}
	return 0
}

func (x *UserProfile) GetAddresses() []*AddressInfo {
	if x != nil {
		return x.Addresses
	}
	return nil
}

// 1. Register
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`              // 可选
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`        // 原始密码 (传输层建议开启 TLS)
	ReqId         string                 `protobuf:"bytes,5,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"` // 幂等性ID (UUID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProfile           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // 注册成功返回完整信息(含地址)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResp) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

// 2. Login
type LoginReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 你的 Service 中 Login 第一个参数是 "account"
	// 前端直接传 input 里的内容，后端自己判断是 email 还是 username
	Account       string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip            string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"` // 对应 Service 的 last_login_ip
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProfile           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_api_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResp) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

// 3. UpdatePassword
type UpdatePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordReq) Reset() {
	*x = UpdatePasswordReq{}
	mi := &file_api_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReq) ProtoMessage() {}

func (x *UpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePasswordReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResp) Reset() {
	*x = UpdatePasswordResp{}
	mi := &file_api_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResp) ProtoMessage() {}

func (x *UpdatePasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResp.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResp) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePasswordResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserInfoReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 使用 oneof，代表一次请求只能传其中一种
	//
	// Types that are valid to be assigned to Query:
	//
	//	*GetUserInfoReq_UserId
	//	*GetUserInfoReq_Username
	//	*GetUserInfoReq_Email
	//	*GetUserInfoReq_Phone
	Query         isGetUserInfoReq_Query `protobuf_oneof:"query"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_api_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoReq) GetQuery() isGetUserInfoReq_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GetUserInfoReq) GetUserId() int64 {
	if x != nil {
		if x, ok := x.Query.(*GetUserInfoReq_UserId); ok {
			return x.UserId
		}
	}
	return 0
}

func (x *GetUserInfoReq) GetUsername() string {
	if x != nil {
		if x, ok := x.Query.(*GetUserInfoReq_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *GetUserInfoReq) GetEmail() string {
	if x != nil {
		if x, ok := x.Query.(*GetUserInfoReq_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *GetUserInfoReq) GetPhone() string {
	if x != nil {
		if x, ok := x.Query.(*GetUserInfoReq_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isGetUserInfoReq_Query interface {
	isGetUserInfoReq_Query()
}

type GetUserInfoReq_UserId struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type GetUserInfoReq_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

type GetUserInfoReq_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

type GetUserInfoReq_Phone struct {
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3,oneof"`
}

func (*GetUserInfoReq_UserId) isGetUserInfoReq_Query() {}

func (*GetUserInfoReq_Username) isGetUserInfoReq_Query() {}

func (*GetUserInfoReq_Email) isGetUserInfoReq_Query() {}

func (*GetUserInfoReq_Phone) isGetUserInfoReq_Query() {}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProfile           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_api_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserInfoResp) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

// 5. UpdateUserStatus
type UpdateUserStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        UserStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=user.v1.UserStatus" json:"status,omitempty"` // 传入 ENABLED 或 DISABLED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusReq) Reset() {
	*x = UpdateUserStatusReq{}
	mi := &file_api_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusReq) ProtoMessage() {}

func (x *UpdateUserStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserStatusReq) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

type UpdateUserStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusResp) Reset() {
	*x = UpdateUserStatusResp{}
	mi := &file_api_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusResp) ProtoMessage() {}

func (x *UpdateUserStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusResp) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserStatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 6. UpdateUserProfile
type UpdateUserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"` // 如果为空则不修改
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"` // 如果为空则不修改
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileReq) Reset() {
	*x = UpdateUserProfileReq{}
	mi := &file_api_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileReq) ProtoMessage() {}

func (x *UpdateUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateUserProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserProfileReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserProfileReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateUserProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileResp) Reset() {
	*x = UpdateUserProfileResp{}
	mi := &file_api_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileResp) ProtoMessage() {}

func (x *UpdateUserProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileResp.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileResp) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserProfileResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 7. GetUserByAddress (Internal)
type GetUserByAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByAddressReq) Reset() {
	*x = GetUserByAddressReq{}
	mi := &file_api_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByAddressReq) ProtoMessage() {}

func (x *GetUserByAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByAddressReq.ProtoReflect.Descriptor instead.
func (*GetUserByAddressReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserByAddressReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetUserByAddressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByAddressResp) Reset() {
	*x = GetUserByAddressResp{}
	mi := &file_api_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByAddressResp) ProtoMessage() {}

func (x *GetUserByAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByAddressResp.ProtoReflect.Descriptor instead.
func (*GetUserByAddressResp) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserByAddressResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_api_user_v1_user_proto protoreflect.FileDescriptor

const file_api_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/v1/user.proto\x12\auser.v1\"=\n" +
	"\vAddressInfo\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x89\x02\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.user.v1.UserStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\"\n" +
	"\rlast_login_at\x18\a \x01(\x03R\vlastLoginAt\x122\n" +
	"\taddresses\x18\b \x03(\v2\x14.user.v1.AddressInfoR\taddresses\"\x88\x01\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x15\n" +
	"\x06req_id\x18\x05 \x01(\tR\x05reqId\"8\n" +
	"\fRegisterResp\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.user.v1.UserProfileR\x04user\"P\n" +
	"\bLoginReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"5\n" +
	"\tLoginResp\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.user.v1.UserProfileR\x04user\"r\n" +
	"\x11UpdatePasswordReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\".\n" +
	"\x12UpdatePasswordResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x82\x01\n" +
	"\x0eGetUserInfoReq\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x04 \x01(\tH\x00R\x05phoneB\a\n" +
	"\x05query\";\n" +
	"\x0fGetUserInfoResp\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.user.v1.UserProfileR\x04user\"[\n" +
	"\x13UpdateUserStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.user.v1.UserStatusR\x06status\"0\n" +
	"\x14UpdateUserStatusResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"[\n" +
	"\x14UpdateUserProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"1\n" +
	"\x15UpdateUserProfileResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x13GetUserByAddressReq\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"/\n" +
	"\x14GetUserByAddressResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId*\\\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14USER_STATUS_DISABLED\x10\x01\x12\x17\n" +
	"\x13USER_STATUS_ENABLED\x10\x022\xf2\x03\n" +
	"\x04User\x127\n" +
	"\bRegister\x12\x14.user.v1.RegisterReq\x1a\x15.user.v1.RegisterResp\x12.\n" +
	"\x05Login\x12\x11.user.v1.LoginReq\x1a\x12.user.v1.LoginResp\x12I\n" +
	"\x0eUpdatePassword\x12\x1a.user.v1.UpdatePasswordReq\x1a\x1b.user.v1.UpdatePasswordResp\x12@\n" +
	"\vGetUserInfo\x12\x17.user.v1.GetUserInfoReq\x1a\x18.user.v1.GetUserInfoResp\x12O\n" +
	"\x10UpdateUserStatus\x12\x1c.user.v1.UpdateUserStatusReq\x1a\x1d.user.v1.UpdateUserStatusResp\x12R\n" +
	"\x11UpdateUserProfile\x12\x1d.user.v1.UpdateUserProfileReq\x1a\x1e.user.v1.UpdateUserProfileResp\x12O\n" +
	"\x10GetUserByAddress\x12\x1c.user.v1.GetUserByAddressReq\x1a\x1d.user.v1.GetUserByAddressRespB\x15Z\x13api/user/v1;user_v1b\x06proto3"

var (
	file_api_user_v1_user_proto_rawDescOnce sync.Once
	file_api_user_v1_user_proto_rawDescData []byte
)

func file_api_user_v1_user_proto_rawDescGZIP() []byte {
	file_api_user_v1_user_proto_rawDescOnce.Do(func() {
		file_api_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)))
	})
	return file_api_user_v1_user_proto_rawDescData
}

var file_api_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_user_v1_user_proto_goTypes = []any{
	(UserStatus)(0),               // 0: user.v1.UserStatus
	(*AddressInfo)(nil),           // 1: user.v1.AddressInfo
	(*UserProfile)(nil),           // 2: user.v1.UserProfile
	(*RegisterReq)(nil),           // 3: user.v1.RegisterReq
	(*RegisterResp)(nil),          // 4: user.v1.RegisterResp
	(*LoginReq)(nil),              // 5: user.v1.LoginReq
	(*LoginResp)(nil),             // 6: user.v1.LoginResp
	(*UpdatePasswordReq)(nil),     // 7: user.v1.UpdatePasswordReq
	(*UpdatePasswordResp)(nil),    // 8: user.v1.UpdatePasswordResp
	(*GetUserInfoReq)(nil),        // 9: user.v1.GetUserInfoReq
	(*GetUserInfoResp)(nil),       // 10: user.v1.GetUserInfoResp
	(*UpdateUserStatusReq)(nil),   // 11: user.v1.UpdateUserStatusReq
	(*UpdateUserStatusResp)(nil),  // 12: user.v1.UpdateUserStatusResp
	(*UpdateUserProfileReq)(nil),  // 13: user.v1.UpdateUserProfileReq
	(*UpdateUserProfileResp)(nil), // 14: user.v1.UpdateUserProfileResp
	(*GetUserByAddressReq)(nil),   // 15: user.v1.GetUserByAddressReq
	(*GetUserByAddressResp)(nil),  // 16: user.v1.GetUserByAddressResp
}
var file_api_user_v1_user_proto_depIdxs = []int32{
	0,  // 0: user.v1.UserProfile.status:type_name -> user.v1.UserStatus
	1,  // 1: user.v1.UserProfile.addresses:type_name -> user.v1.AddressInfo
	2,  // 2: user.v1.RegisterResp.user:type_name -> user.v1.UserProfile
	2,  // 3: user.v1.LoginResp.user:type_name -> user.v1.UserProfile
	2,  // 4: user.v1.GetUserInfoResp.user:type_name -> user.v1.UserProfile
	0,  // 5: user.v1.UpdateUserStatusReq.status:type_name -> user.v1.UserStatus
	3,  // 6: user.v1.User.Register:input_type -> user.v1.RegisterReq
	5,  // 7: user.v1.User.Login:input_type -> user.v1.LoginReq
	7,  // 8: user.v1.User.UpdatePassword:input_type -> user.v1.UpdatePasswordReq
	9,  // 9: user.v1.User.GetUserInfo:input_type -> user.v1.GetUserInfoReq
	11, // 10: user.v1.User.UpdateUserStatus:input_type -> user.v1.UpdateUserStatusReq
	13, // 11: user.v1.User.UpdateUserProfile:input_type -> user.v1.UpdateUserProfileReq
	15, // 12: user.v1.User.GetUserByAddress:input_type -> user.v1.GetUserByAddressReq
	4,  // 13: user.v1.User.Register:output_type -> user.v1.RegisterResp
	6,  // 14: user.v1.User.Login:output_type -> user.v1.LoginResp
	8,  // 15: user.v1.User.UpdatePassword:output_type -> user.v1.UpdatePasswordResp
	10, // 16: user.v1.User.GetUserInfo:output_type -> user.v1.GetUserInfoResp
	12, // 17: user.v1.User.UpdateUserStatus:output_type -> user.v1.UpdateUserStatusResp
	14, // 18: user.v1.User.UpdateUserProfile:output_type -> user.v1.UpdateUserProfileResp
	16, // 19: user.v1.User.GetUserByAddress:output_type -> user.v1.GetUserByAddressResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_user_v1_user_proto_init() }
func file_api_user_v1_user_proto_init() {
	if File_api_user_v1_user_proto != nil {
		return
	}
	file_api_user_v1_user_proto_msgTypes[8].OneofWrappers = []any{
		(*GetUserInfoReq_UserId)(nil),
		(*GetUserInfoReq_Username)(nil),
		(*GetUserInfoReq_Email)(nil),
		(*GetUserInfoReq_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_user_proto_goTypes,
		DependencyIndexes: file_api_user_v1_user_proto_depIdxs,
		EnumInfos:         file_api_user_v1_user_proto_enumTypes,
		MessageInfos:      file_api_user_v1_user_proto_msgTypes,
	}.Build()
	File_api_user_v1_user_proto = out.File
	file_api_user_v1_user_proto_goTypes = nil
	file_api_user_v1_user_proto_depIdxs = nil
}
