# 基础镜像
FROM golang:1.25.4
# 设置工作目录 
WORKDIR /app
# 复制需要下载的文件
COPY go.mod go.sum /
# 进行下载 
RUN  go mod download
# 复制源代码
COPY . .
# 运行代码
CMD ["go","run","./apps/wallet/cmd/main.go","-f","./apps/wallet/etc/wallet.yaml"]