package domain

type WalletRepo interface {
	AddressRepo  // 包含 SaveAddress, GetUserId... Transaction
	AssetRepo    // 包含 AddBalance...
	Repository   // 包含 ConfirmDeposits...
	WithdrawRepo // 包含 FreezeBalance, CreateWithdrawOrder...
}
